version: "3"

services:
  pierreduplouy-back:
    container_name: pierreduplouy_back
    restart: always
    image: pierreduplouy_back
    build: ./back
    volumes:
      - ./private:/private
    ports:
      - 5000:5000

  pierreduplouy-nginx:
    container_name: pierreduplouy_nginx
    restart: always
    image: nginx:latest
    volumes:
      - ./private:/private/private
      - ./nginx/private.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - 5001:5001
