version: "3"

services:

  pierreduplouy-front:
    container_name: pierreduplouy
    restart: always
    image: pierreduplouy
    build: .
    networks:
      - traefik
    labels:
      - "traefik.frontend.rule=Host:pierreduplouy.fr, www.pierreduplouy.fr"
      - "traefik.port=80"
      - "traefik.backend=pierreduplouy"
      - "traefik.frontend.entryPoints=http,https"
      - "traefik.docker.network=traefik_traefik"
      - "traefik.default.protocol=http"

networks:
  traefik:
    external:
      name: traefik_traefik
