- hosts: prod
  tasks:
    - name: create dest repertory
      file: path=/srv/pierreduplouy state=directory owner=nyhu group=nyhu
      become: yes

    - name: copy {{ item }}
      copy: src={{ item }} dest=/srv/pierreduplouy/.
         owner=nyhu group=nyhu mode=0644
      with_items:
        - Dockerfile
        - docker-compose.yml
        - front/dist
        - nginx
        - back
        - private
      become: yes

    - name: run service
      command: docker-compose up -d --build --remove-orphan
      args:
        chdir: /srv/pierreduplouy/
      become: yes
